chart:
  chartRefreshInterval: 0.25
  enAnimation: false
  isLinkEmpty: false
serial:
- baud: '9600'
  chann:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  deviceType: CowRobot
  name: 设备1
  port: COM18
view:
  showLatestView: 200
  showLiveData: true
